#cloud-config
package_update: true
packages:
  - docker.io
  - docker-compose
runcmd:
  - systemctl enable docker
  - systemctl start docker
  - mkdir -p /opt/cicd
  - curl -fsSL https://raw.githubusercontent.com/SEU_USUARIO/SEU_REPO/main/cicd/docker-compose.yml -o /opt/cicd/docker-compose.yml
  - docker compose -f /opt/cicd/docker-compose.yml up -d
